config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :posts
   get '/space' => 'posts#space'
   get '/health' => 'posts#health'
   get '/tech' => 'posts#tech'
   get '/science' => 'posts#science'
   get '/environment' => 'posts#environment'
   get '/earth' => 'posts#earth'
   get '/education' => 'posts#education'
   get '/society' => 'posts#society'
   get '/arts' => 'posts#arts'
   get '/all' => 'posts#all'

  root 'posts#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_inclusion_of :name, in: Choices['name']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def set_admin_timezone
    Time.zone = 'Eastern Time (US & Canada)'
  end

end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base

  def index
    @posts = Post.all
  end

  def show
    @post = get_post
  end

  def all
    @posts = Post.all
  end

  def space
    @posts = Post.all
  end

  def health
    @posts = Post.all
  end

  def tech
    @posts = Post.all
  end

  def science
    @posts = Post.all
  end

  def environment
    @posts = Post.all
  end

  def earth
    @posts = Post.all
  end

  def education
    @posts = Post.all
  end

  def society
    @posts = Post.all
  end

  def arts
    @posts = Post.all
  end

  private

    def post_params
      params.require(:post).permit(:name, :title, :content, :source, :created_at)
    end

    def get_post
      Post.find(params[:id])
    end

    # def get_category
    #   Post.find(params[:name])
    # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href='https://fonts.googleapis.com/css?family=Montserrat|Source+Sans+Pro' rel='stylesheet' type='text/css'>
    <title><%= content_for?(:title) ? yield(:title) : "Rad Planet" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/all.html.erb
<div class="all-container">
<%= link_to root_path do %>
<div class="all-description second-homeParallax large-12 medium-12 small-12 columns"><h1>RAD PLANET</h1></div>
<% end %>
</div>
<ul class="sub-nav menu" role="navigation" title="Filter Menu List">
  <li class="sub-nav-title">Categories:</li>
  <li><a href="/">Home</a></li>
  <li class="active"><span class="show-for-sr">You're viewing </span><a href="/all">All</a></li>
  <li><a href="/arts">Arts</a></li>
  <li><a href="/earth">Earth</a></li>
  <li><a href="/education">Education</a></li>
  <li><a href="/environment">Environment</a></li>
  <li><a href="/health">Health</a></li>
  <li><a href="/science">Science</a></li>
  <li><a href="/society">Society</a></li>
  <li><a href="/space">Space</a></li>
  <li><a href="/tech">Tech</a></li>
</ul>
<div class="recent-posts large-12 medium-12 small-12 columns"><h2>All Discoveries</h2></div>
<% @posts.reverse.each do |post| %>
<div class="home-date"> <h4><%= post.created_at.strftime("%B %d, %Y") %></h4> </div>
<div class="horizontal-callout-card">
  <div class="row column medium-8" data-equalizer>
    <div class="row collapse">
      <div class="column medium-3">
        <div class="callout secondary first-section" data-equalizer-watch>
          <strong><p><%= post.title %></p></strong>
        </div>
      </div>
      <div class="column medium-6">
        <div class="callout middle-section" data-equalizer-watch>
          <p><%= truncate(post.content, length: 300, omission: '...') { link_to "Read more", "posts/#{post.id}" } %></p>
        </div>
      </div>
      <div class="column medium-3">
        <div class="callout secondary last-section" data-equalizer-watch>
          <p><%= link_to post.name, "#{post.name}".downcase %></p><br>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/arts.html.erb
<div class="all-container">
<%= link_to root_path do %>
<div class="arts-description second-homeParallax large-12 medium-12 small-12 columns"><h1>RAD PLANET</h1></div>
<% end %>
</div>
<ul class="sub-nav menu" role="navigation" title="Filter Menu List">
  <li class="sub-nav-title">Categories:</li>
  <li><a href="/">Home</a></li>
  <li><a href="/all">All</a></li>
  <li class="active"><span class="show-for-sr">You're viewing </span><a href="/">Arts</a></li>
  <li><a href="/earth">Earth</a></li>
  <li><a href="/education">Education</a></li>
  <li><a href="/environment">Environment</a></li>
  <li><a href="/health">Health</a></li>
  <li><a href="/science">Science</a></li>
  <li><a href="/society">Society</a></li>
  <li><a href="/space">Space</a></li>
  <li><a href="/tech">Tech</a></li>
</ul>
<div class="recent-posts large-12 medium-12 small-12 columns"><h2>The Arts</h2></div>
<% @posts.where("name = 'Arts'").reverse.each do |post| %>
<div class="home-date"> <h4><%= post.created_at.strftime("%B %d, %Y") %></h4> </div>
<div class="horizontal-callout-card">
  <div class="row column medium-8" data-equalizer>
    <div class="row collapse">
      <div class="column medium-3">
        <div class="callout secondary first-section" data-equalizer-watch>
          <strong><p><%= post.title %></p></strong>
        </div>
      </div>
      <div class="column medium-6">
        <div class="callout middle-section" data-equalizer-watch>
          <p><%= truncate(post.content, length: 300, omission: '...') { link_to "Read more", "posts/#{post.id}" } %></p>
        </div>
      </div>
      <div class="column medium-3">
        <div class="callout secondary last-section" data-equalizer-watch>
          <p><%= post.name %></p><br>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/earth.html.erb
<div class="all-container">
<%= link_to root_path do %>
<div class="earth-description second-homeParallax large-12 medium-12 small-12 columns"><h1>RAD PLANET</h1></div>
<% end %>
</div>
<ul class="sub-nav menu" role="navigation" title="Filter Menu List">
  <li class="sub-nav-title">Categories:</li>
  <li><a href="/">Home</a></li>
  <li><a href="/all">All</a></li>
  <li><a href="/arts">Arts</a></li>
  <li class="active"><span class="show-for-sr">You're viewing </span><a href="/earth">Earth</a></li>
  <li><a href="/education">Education</a></li>
  <li><a href="/environment">Environment</a></li>
  <li><a href="/health">Health</a></li>
  <li><a href="/science">Science</a></li>
  <li><a href="/society">Society</a></li>
  <li><a href="/space">Space</a></li>
  <li><a href="/tech">Tech</a></li>
</ul>
<div class="recent-posts large-12 medium-12 small-12 columns"><h2>Earth</h2></div>
<% @posts.where("name = 'Earth'").reverse.each do |post| %>
<div class="home-date"> <h4><%= post.created_at.strftime("%B %d, %Y") %></h4> </div>
<div class="horizontal-callout-card">
  <div class="row column medium-8" data-equalizer>
    <div class="row collapse">
      <div class="column medium-3">
        <div class="callout secondary first-section" data-equalizer-watch>
          <strong><p><%= post.title %></p></strong>
        </div>
      </div>
      <div class="column medium-6">
        <div class="callout middle-section" data-equalizer-watch>
          <p><%= truncate(post.content, length: 300, omission: '...') { link_to "Read more", "posts/#{post.id}" } %></p>
        </div>
      </div>
      <div class="column medium-3">
        <div class="callout secondary last-section" data-equalizer-watch>
          <p><%= post.name %></p><br>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/education.html.erb
<div class="all-container">
<%= link_to root_path do %>
<div class="education-description second-homeParallax large-12 medium-12 small-12 columns"><h1>RAD PLANET</h1></div>
<% end %>
</div>
<ul class="sub-nav menu" role="navigation" title="Filter Menu List">
  <li class="sub-nav-title">Categories:</li>
  <li><a href="/">Home</a></li>
  <li><a href="/all">All</a></li>
  <li><a href="/arts">Arts</a></li>
  <li><a href="/earth">Earth</a></li>
  <li class="active"><span class="show-for-sr">You're viewing </span><a href="/education">Education</a></li>
  <li><a href="/environment">Environment</a></li>
  <li><a href="/health">Health</a></li>
  <li><a href="/science">Science</a></li>
  <li><a href="/society">Society</a></li>
  <li><a href="/space">Space</a></li>
  <li><a href="/tech">Tech</a></li>
</ul>
<div class="recent-posts large-12 medium-12 small-12 columns"><h2>Education</h2></div>
<% @posts.where("name = 'Education'").reverse.each do |post| %>
<div class="home-date"> <h4><%= post.created_at.strftime("%B %d, %Y") %></h4> </div>
<div class="horizontal-callout-card">
  <div class="row column medium-8" data-equalizer>
    <div class="row collapse">
      <div class="column medium-3">
        <div class="callout secondary first-section" data-equalizer-watch>
          <strong><p><%= post.title %></p></strong>
        </div>
      </div>
      <div class="column medium-6">
        <div class="callout middle-section" data-equalizer-watch>
          <p><%= truncate(post.content, length: 300, omission: '...') { link_to "Read more", "posts/#{post.id}" } %></p>
        </div>
      </div>
      <div class="column medium-3">
        <div class="callout secondary last-section" data-equalizer-watch>
          <p><%= post.name %></p><br>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/environment.html.erb
<div class="all-container">
<%= link_to root_path do %>
<div class="environment-description second-homeParallax large-12 medium-12 small-12 columns"><h1>RAD PLANET</h1></div>
<% end %>
</div>
<ul class="sub-nav menu" role="navigation" title="Filter Menu List">
  <li class="sub-nav-title">Categories:</li>
  <li><a href="/">Home</a></li>
  <li><a href="/all">All</a></li>
  <li><a href="/arts">Arts</a></li>
  <li><a href="/earth">Earth</a></li>
  <li><a href="/education">Education</a></li>
  <li class="active"><span class="show-for-sr">You're viewing </span><a href="/environment">Environment</a></li>
  <li><a href="/health">Health</a></li>
  <li><a href="/science">Science</a></li>
  <li><a href="/society">Society</a></li>
  <li><a href="/space">Space</a></li>
  <li><a href="/tech">Tech</a></li>
</ul>
<div class="recent-posts large-12 medium-12 small-12 columns"><h2>Environment</h2></div>
<% @posts.where("name = 'Environment'").reverse.each do |post| %>
<div class="home-date"> <h4><%= post.created_at.strftime("%B %d, %Y") %></h4> </div>
<div class="horizontal-callout-card">
  <div class="row column medium-8" data-equalizer>
    <div class="row collapse">
      <div class="column medium-3">
        <div class="callout secondary first-section" data-equalizer-watch>
          <strong><p><%= post.title %></p></strong>
        </div>
      </div>
      <div class="column medium-6">
        <div class="callout middle-section" data-equalizer-watch>
          <p><%= truncate(post.content, length: 300, omission: '...') { link_to "Read more", "posts/#{post.id}" } %></p>
        </div>
      </div>
      <div class="column medium-3">
        <div class="callout secondary last-section" data-equalizer-watch>
          <p><%= post.name %></p><br>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/health.html.erb
<div class="all-container">
<%= link_to root_path do %>
<div class="health-description second-homeParallax large-12 medium-12 small-12 columns"><h1>RAD PLANET</h1></div>
<% end %>
</div>
<ul class="sub-nav menu" role="navigation" title="Filter Menu List">
  <li class="sub-nav-title">Categories:</li>
  <li><a href="/">Home</a></li>
  <li><a href="/all">All</a></li>
  <li><a href="/arts">Arts</a></li>
  <li><a href="/earth">Earth</a></li>
  <li><a href="/education">Education</a></li>
  <li><a href="/environment">Environment</a></li>
  <li class="active"><span class="show-for-sr">You're viewing </span><a href="/health">Health</a></li>
  <li><a href="/science">Science</a></li>
  <li><a href="/society">Society</a></li>
  <li><a href="/space">Space</a></li>
  <li><a href="/tech">Tech</a></li>
</ul>
<div class="recent-posts large-12 medium-12 small-12 columns"><h2>Health</h2></div>
<% @posts.where("name = 'Health'").reverse.each do |post| %>
<div class="home-date"> <h4><%= post.created_at.strftime("%B %d, %Y") %></h4> </div>
<div class="horizontal-callout-card">
  <div class="row column medium-8" data-equalizer>
    <div class="row collapse">
      <div class="column medium-3">
        <div class="callout secondary first-section" data-equalizer-watch>
          <strong><p><%= post.title %></p></strong>
        </div>
      </div>
      <div class="column medium-6">
        <div class="callout middle-section" data-equalizer-watch>
          <p><%= truncate(post.content, length: 300, omission: '...') { link_to "Read more", "posts/#{post.id}" } %></p>
        </div>
      </div>
      <div class="column medium-3">
        <div class="callout secondary last-section" data-equalizer-watch>
          <p><%= post.name %></p><br>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="home-container">
  <div class="home-myParallax large-12 medium-12 small-12 columns">
    <h1>RAD PLANET</h1>
  </div>
</div>
<div class="home-container2">
<div class="home-description1 second-homeParallax large-12 medium-12 small-12 columns"><h1>Our Planet Is Amazing.</h1></div>
</div>
<div class="home-container3">
<div class="home-description2 second-homeParallax large-12 medium-12 small-12 columns"><h1>Remind Yourself. Once a Day.</h1></div>
</div>
<ul class="sub-nav menu" role="navigation" title="Filter Menu List">
  <li class="sub-nav-title">Categories:</li>
  <li class="active"><span class="show-for-sr">You're viewing </span><a href="/">Home</a></li>
  <li><a href="/all">All</a></li>
  <li><a href="/arts">Arts</a></li>
  <li><a href="/earth">Earth</a></li>
  <li><a href="/education">Education</a></li>
  <li><a href="/environment">Environment</a></li>
  <li><a href="/health">Health</a></li>
  <li><a href="/science">Science</a></li>
  <li><a href="/society">Society</a></li>
  <li><a href="/space">Space</a></li>
  <li><a href="/tech">Tech</a></li>
</ul>
<div class="recent-posts large-12 medium-12 small-12 columns"><h2>Recent Discoveries</h2></div>
<% @posts.reverse.first(10).each do |post| %>
<div class="home-date"> <h4><%= post.created_at.strftime("%B %d, %Y") %></h4> </div>
<div class="horizontal-callout-card">
  <div class="row column medium-8" data-equalizer>
    <div class="row collapse">
      <div class="column medium-3">
        <div class="callout secondary first-section" data-equalizer-watch>
          <strong><p><%= post.title %></p></strong>
        </div>
      </div>
      <div class="column medium-6">
        <div class="callout middle-section" data-equalizer-watch>
          <p><%= truncate(post.content, length: 300, omission: '...') { link_to "Read more", "posts/#{post.id}" } %></p>
        </div>
      </div>
      <div class="column medium-3">
        <div class="callout secondary last-section" data-equalizer-watch>
          <p><%= link_to post.name, "#{post.name}".downcase %></p><br>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
<div class="all-link">
<%= link_to all_path do %>
  <p>Read All</p>
</div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="all-container">
<%= link_to root_path do %>
<div class="<%= @post.name.downcase %>-description second-homeParallax large-12 medium-12 small-12 columns"><h1>RAD PLANET</h1></div>
<% end %>

</div>
<div id="indiv-post-container">
<h5><%= @post.created_at.strftime("%B %d, %Y") %></h5>

<h4>
  <strong><%= @post.title %></strong>
</h4>

<div class="indiv-post">
<p>
  <%= @post.content %>
</p>
</div>

<p>
  <strong>Source:</strong>
  <%= link_to @post.source, "#{@post.source}" %><br>
</p>

<p>
  <strong>Category:</strong>
  <%= link_to @post.name, "/#{@post.name}".downcase %><br>
</p>

<%= link_to 'Back to Homepage', posts_path %><br>

</div><br>

app/views/posts/society.html.erb
<div class="all-container">
<%= link_to root_path do %>
<div class="society-description second-homeParallax large-12 medium-12 small-12 columns"><h1>RAD PLANET</h1></div>
<% end %>
</div>
<ul class="sub-nav menu" role="navigation" title="Filter Menu List">
  <li class="sub-nav-title">Categories:</li>
  <li><a href="/">Home</a></li>
  <li><a href="/all">All</a></li>
  <li><a href="/arts">Arts</a></li>
  <li><a href="/earth">Earth</a></li>
  <li><a href="/education">Education</a></li>
  <li><a href="/environment">Environment</a></li>
  <li><a href="/health">Health</a></li>
  <li><a href="/science">Science</a></li>
  <li class="active"><span class="show-for-sr">You're viewing </span><a href="/society">Society</a></li>
  <li><a href="/space">Space</a></li>
  <li><a href="/tech">Tech</a></li>
</ul>
<div class="recent-posts large-12 medium-12 small-12 columns"><h2>Society</h2></div>
<% @posts.where("name = 'Society'").reverse.each do |post| %>
<div class="home-date"> <h4><%= post.created_at.strftime("%B %d, %Y") %></h4> </div>
<div class="horizontal-callout-card">
  <div class="row column medium-8" data-equalizer>
    <div class="row collapse">
      <div class="column medium-3">
        <div class="callout secondary first-section" data-equalizer-watch>
          <strong><p><%= post.title %></p></strong>
        </div>
      </div>
      <div class="column medium-6">
        <div class="callout middle-section" data-equalizer-watch>
          <p><%= truncate(post.content, length: 300, omission: '...') { link_to "Read more", "posts/#{post.id}" } %></p>
        </div>
      </div>
      <div class="column medium-3">
        <div class="callout secondary last-section" data-equalizer-watch>
          <p><%= post.name %></p><br>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/space.html.erb
<div class="all-container">
<%= link_to root_path do %>
<div class="space-description second-homeParallax large-12 medium-12 small-12 columns"><h1>RAD PLANET</h1></div>
<% end %>
</div>
<ul class="sub-nav menu" role="navigation" title="Filter Menu List">
  <li class="sub-nav-title">Categories:</li>
  <li><a href="/">Home</a></li>
  <li><a href="/all">All</a></li>
  <li><a href="/arts">Arts</a></li>
  <li><a href="/earth">Earth</a></li>
  <li><a href="/education">Education</a></li>
  <li><a href="/environment">Environment</a></li>
  <li><a href="/health">Health</a></li>
  <li><a href="/science">Science</a></li>
  <li><a href="/society">Society</a></li>
  <li class="active"><span class="show-for-sr">You're viewing </span><a href="/space">Space</a></li>
  <li><a href="/tech">Tech</a></li>
</ul>
<div class="recent-posts large-12 medium-12 small-12 columns"><h2>Space</h2></div>
<% @posts.where("name = 'Space'").reverse.each do |post| %>
<div class="home-date"> <h4><%= post.created_at.strftime("%B %d, %Y") %></h4> </div>
<div class="horizontal-callout-card">
  <div class="row column medium-8" data-equalizer>
    <div class="row collapse">
      <div class="column medium-3">
        <div class="callout secondary first-section" data-equalizer-watch>
          <strong><p><%= post.title %></p></strong>
        </div>
      </div>
      <div class="column medium-6">
        <div class="callout middle-section" data-equalizer-watch>
          <p><%= truncate(post.content, length: 300, omission: '...') { link_to "Read more", "posts/#{post.id}" } %></p>
        </div>
      </div>
      <div class="column medium-3">
        <div class="callout secondary last-section" data-equalizer-watch>
          <p><%= post.name %></p><br>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/tech.html.erb
<div class="all-container">
<%= link_to root_path do %>
<div class="tech-description second-homeParallax large-12 medium-12 small-12 columns"><h1>RAD PLANET</h1></div>
<% end %>
</div>
<ul class="sub-nav menu" role="navigation" title="Filter Menu List">
  <li class="sub-nav-title">Categories:</li>
  <li><a href="/">Home</a></li>
  <li><a href="/all">All</a></li>
  <li><a href="/arts">Arts</a></li>
  <li><a href="/earth">Earth</a></li>
  <li><a href="/education">Education</a></li>
  <li><a href="/environment">Environment</a></li>
  <li><a href="/health">Health</a></li>
  <li><a href="/science">Science</a></li>
  <li><a href="/society">Society</a></li>
  <li><a href="/space">Space</a></li>
  <li class="active"><span class="show-for-sr">You're viewing </span><a href="/tech">Tech</a></li>
</ul>
<div class="recent-posts large-12 medium-12 small-12 columns"><h2>Technology</h2></div>
<% @posts.where("name = 'Tech'").reverse.each do |post| %>
<div class="home-date"> <h4><%= post.created_at.strftime("%B %d, %Y") %></h4> </div>
<div class="horizontal-callout-card">
  <div class="row column medium-8" data-equalizer>
    <div class="row collapse">
      <div class="column medium-3">
        <div class="callout secondary first-section" data-equalizer-watch>
          <strong><p><%= post.title %></p></strong>
        </div>
      </div>
      <div class="column medium-6">
        <div class="callout middle-section" data-equalizer-watch>
          <p><%= truncate(post.content, length: 300, omission: '...') { link_to "Read more", "posts/#{post.id}" } %></p>
        </div>
      </div>
      <div class="column medium-3">
        <div class="callout secondary last-section" data-equalizer-watch>
          <p><%= post.name %></p><br>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>